### ISSUE TITLE
"Internal Server" Error on "Get Vehicles" on Type "Seat Cupra"

### ISSUE THREAD

**Issue by jb-tool** [TA2k/ioBroker.vw-connect#213]
**Describe the bug**  
No Objects are created after configuring the instance with type "Seat Cupra"
Got following output in error Log:

> {"code":"internal-error","message":"Internal server error","rootMessage":null,"timestamp":"2022-10-27T13:14:53.005973Z"}
> 500
> Get Vehicles Failed

**To Reproduce**  
1. Install adapter
2. Configure type for seat cupra account (credentials equal to those used in official app)
3. restart instance

**Expected behavior**  
Expected loading all info from cupra server without error

**Screenshots & Logfiles**  

```
2022-10-27 15:21:29.654  - silly: vw-connect.0 (792069) States system redis pmessage system.adapter.vw-connect.0.sigKill/system.adapter.vw-connect.0.sigKill:{"val":-1,"ack":false,"ts":1666876800000,"q":0,"from":"system.host.iobroker","lc":1666800000000}
2022-10-27 15:21:29.658  - info: vw-connect.0 (792069) Got terminate signal TERMINATE_YOURSELF
2022-10-27 15:21:29.665  - info: vw-connect.0 (792069) cleaned everything up...
2022-10-27 15:21:29.669  - info: vw-connect.0 (792069) terminating
2022-10-27 15:21:29.673  - debug: vw-connect.0 (792069) Plugin sentry destroyed
2022-10-27 15:21:29.676  - info: vw-connect.0 (792069) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2022-10-27 15:21:29.756  - silly: vw-connect.0 (792069) States user redis pmessage vw-connect.0.*/vw-connect.0.info.connection:{"val":false,"ack":true,"ts":1666800000000,"q":0,"from":"system.adapter.vw-connect.0","user":"system.user.admin","lc":1666800000000}
2022-10-27 15:21:34.154  - debug: vw-connect.0 (792553) Redis Objects: Use Redis connection: 127.0.0.1:9001
2022-10-27 15:21:34.290  - debug: vw-connect.0 (792553) Objects client ready ... initialize now
2022-10-27 15:21:34.293  - debug: vw-connect.0 (792553) Objects create System PubSub Client
2022-10-27 15:21:34.294  - debug: vw-connect.0 (792553) Objects create User PubSub Client
2022-10-27 15:21:34.371  - debug: vw-connect.0 (792553) Objects client initialize lua scripts
2022-10-27 15:21:34.379  - debug: vw-connect.0 (792553) Objects connected to redis: 127.0.0.1:9001
2022-10-27 15:21:34.381  - silly: vw-connect.0 (792553) redis psubscribe cfg.o.system.user.*
2022-10-27 15:21:34.452  - silly: vw-connect.0 (792553) redis psubscribe cfg.o.enum.*
2022-10-27 15:21:34.456  - silly: vw-connect.0 (792553) objectDB connected
2022-10-27 15:21:34.459  - debug: vw-connect.0 (792553) Redis States: Use Redis connection: 127.0.0.1:9000
2022-10-27 15:21:34.510  - debug: vw-connect.0 (792553) States create System PubSub Client
2022-10-27 15:21:34.511  - debug: vw-connect.0 (792553) States create User PubSub Client
2022-10-27 15:21:34.605  - debug: vw-connect.0 (792553) States connected to redis: 127.0.0.1:9000
2022-10-27 15:21:34.606  - silly: vw-connect.0 (792553) statesDB connected
2022-10-27 15:21:34.856  - debug: vw-connect.0 (792553) Plugin sentry Initialize Plugin (enabled=true)
2022-10-27 15:21:35.377  - info: vw-connect.0 (792553) starting. Version 0.0.53 in /opt/iobroker/node_modules/iobroker.vw-connect, node: v16.17.1, js-controller: 4.0.23
2022-10-27 15:21:36.107  - silly: vw-connect.0 (792553) States system redis pmessage system.adapter.vw-connect.0.logLevel/system.adapter.vw-connect.0.logLevel:{"val":"silly","ack":true,"ts":1666876895670,"q":0,"from":"system.adapter.vw-connect.0","lc":1665500000000}
2022-10-27 15:21:36.159  - silly: vw-connect.0 (792553) States user redis pmessage vw-connect.0.*/vw-connect.0.info.connection:{"val":false,"ack":true,"ts":1666876896154,"q":0,"from":"system.adapter.vw-connect.0","user":"system.user.admin","lc":16668000000000}
2022-10-27 15:21:37.212  - debug: vw-connect.0 (792553) parseEmailForm
2022-10-27 15:21:37.748  - debug: vw-connect.0 (792553) emailPasswordForm2
2022-10-27 15:21:38.323  - debug: vw-connect.0 (792553) ""
2022-10-27 15:21:38.324  - debug: vw-connect.0 (792553) {"date":"Thu, 27 Oct 2022 13:21:38 GMT","content-length":"0","connection":"close","cache-control":"no-cache, no-store, max-age=0, must-revalidate","content-language":"en-US","expires":"0","location":"https://identity.vwgroup.io/oidc/v1/oauth/sso?clientId=000000000-xxxx-xxxx-9f9a-cff0xxxxxxxx@apps_vw-dilab_com&relayState=xxxxxxxxba85a010xxxxxxxxd82ca46axxxxxxxx&userId=xxxxxxxx-xxxxx-xxxx-xxxxx-3692xxxxxxxx&HMAC=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","pragma":"no-cache","strict-transport-security":"max-age=31536000 ; includeSubDomains","x-content-type-options":"nosniff","x-frame-options":"DENY","x-vcap-request-id":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx","x-xss-protection":"1; mode=block"}
2022-10-27 15:21:39.070  - debug: vw-connect.0 (792553) Error: Invalid protocol: cupra:
2022-10-27 15:21:39.410  - info: vw-connect.0 (792553) Login successful
2022-10-27 15:21:39.420  - silly: vw-connect.0 (792553) States user redis pmessage vw-connect.0.*/vw-connect.0.info.connection:{"val":true,"ack":true,"ts":1666876899418,"q":0,"from":"system.adapter.vw-connect.0","user":"system.user.admin","lc":16668000000000}
2022-10-27 15:21:39.954  - error: vw-connect.0 (792553) {"code":"internal-error","message":"Internal server error","rootMessage":null,"timestamp":"2022-10-27T13:21:39.939108Z"}
2022-10-27 15:21:39.955  - error: vw-connect.0 (792553) 500
2022-10-27 15:21:39.955  - error: vw-connect.0 (792553) Get Vehicles Failed
```

**Versions:**  
 - Adapter version: error occured in version 0.0.51, 0.0.52, 0.0.53 but maybe also before?
 - JS-Controller version: 4.0.23
 - Node version: 16.17.1 but error also occured with version 14.x
 - Operating system: Linux iobroker 5.10.0-14-amd64  SMP Debian 5.10.113-1

**Comment by TA2k** [comment]
looks like an error on vw side should be fixed

**Comment by jb-tool** [comment]
This error still occures. So i think this is a permanent error and not a temporary one. Since connection by the cupra app works without problems.
Seems like there has been an similar error on vw  (#200)

Is it possible that this error is related to the "shutdown of the cupra portal" ?

https://www.cupraofficial.at/cupra-connect/connect-app
> Das CONNECT Portal wurde deaktiviert.
>  
> Ab dem 22. April 2022 ist das CUPRA CONNECT Portal nicht mehr online verfügbar. Lade dir die CUPRA CONNECT App herunter

@TA2k it would be great if you can have a closer look to the problem.

**Comment by TA2k** [comment]
I can do this but need an account to test this
tombox2020@gmail.com
